name: Flutter CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - release/*
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Tests
      run: flutter test

    - name: Code Coverage
      run: flutter test --coverage

    - name: Analyze Code
      run: flutter analyze

    - name: Notify Discord
      run: |
        DATE=$(date +%d/%m/%Y)
        BUILD_RESULT=$(if [ ${{ job.status }} == 'success' ]; then echo '\u2705'; else echo '\u274c'; fi)
        BUILD_RESULT_COLOR=$(if [ ${{ job.status }} == 'success' ]; then echo '12076871'; else echo '4700231'; fi)
        curl -X POST "https://discord.com/api/webhooks/YOUR_DISCORD_WEBHOOK_URL" -H "Content-Type:application/json" -d "{\"content\":null,\"embeds\":[{\"title\":\"Workflow ${{ github.run_id }}\",\"description\":\"A workflow terminou com status $BUILD_RESULT\",\"url\":\"${{ github.event.repository.html_url }}\",\"color\":$BUILD_RESULT_COLOR,\"author\":{\"name\":\"${{ github.repository }}\",\"url\":\"${{ github.event.repository.html_url }}\"},\"footer\":{\"text\":\"${{ github.head_ref }} \u2022 $DATE\"}}]}"

  build_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'

    - name: Build and Upload APK
      run: |
        VERSION=$(grep version pubspec.yaml | tail -1 | cut -d ":" -f 2 | xargs)
        PACKAGE=$(cd android/app/src/main && grep package AndroidManifest.xml | tail -1 | cut -d '"' -f 4)
        echo ${PACKAGE}-${VERSION}
        flutter build apk --release run --flavor homo -t lib/main_homo.dart
        cd build/app/outputs/flutter-apk/
        mv app-homo-release.apk ${PACKAGE}-${VERSION}.apk
        echo "::set-output name=filename::${PACKAGE}-${VERSION}.apk"

    - name: Upload to Releases
      uses: actions/upload-release-asset@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/app/outputs/flutter-apk/${{ needs.build_release.outputs.filename }}
        asset_name: ${{ needs.build_release.outputs.filename }}
        tag: ${{ github.ref }}

    - name: Notify Discord
      run: |
        DATE=$(date +%d/%m/%Y)
        BUILD_RESULT=$(if [ ${{ job.status }} == 'success' ]; then echo '\u2705'; else echo '\u274c'; fi)
        BUILD_RESULT_COLOR=$(if [ ${{ job.status }} == 'success' ]; then echo '12076871'; else echo '4700231'; fi)
        curl -X POST "https://discord.com/api/webhooks/YOUR_DISCORD_WEBHOOK_URL" -H "Content-Type:application/json" -d "{\"content\":null,\"embeds\":[{\"title\":\"Workflow ${{ github.run_id }}\",\"description\":\"A workflow terminou com status $BUILD_RESULT\",\"url\":\"${{ github.event.repository.html_url }}\",\"color\":$BUILD_RESULT_COLOR,\"author\":{\"name\":\"${{ github.repository }}\",\"url\":\"${{ github.event.repository.html_url }}\"},\"footer\":{\"text\":\"${{ github.head_ref }} \u2022 $DATE\"}}]}"

  build_master:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'

    - name: Build and Upload APK
      run: |
        VERSION=$(grep version pubspec.yaml | tail -1 | cut -d ":" -f 2 | xargs)
        PACKAGE=$(cd android/app/src/main && grep package AndroidManifest.xml | tail -1 | cut -d '"' -f 4)
        echo ${PACKAGE}-${VERSION}
        flutter build apk --release run --flavor prod -t lib/main_prod.dart
        cd build/app/outputs/flutter-apk/
        mv app-prod-release.apk ${PACKAGE}-${VERSION}.apk
        echo "::set-output name=filename::${PACKAGE}-${VERSION}.apk"

    - name: Upload to Releases
      uses: actions/upload-release-asset@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/app/outputs/flutter-apk/${{ needs.build_master.outputs.filename }}
        asset_name: ${{ needs.build_master.outputs.filename }}
        tag: ${{ github.ref }}

    - name: Notify Discord
      run: |
        DATE=$(date +%d/%m/%Y)
        BUILD_RESULT=$(if [ ${{ job.status }} == 'success' ]; then echo '\u2705'; else echo '\u274c'; fi)
        BUILD_RESULT_COLOR=$(if [ ${{ job.status }} == 'success' ]; then echo '12076871'; else echo '4700231'; fi)
        curl -X POST "https://discord.com/api/webhooks/YOUR_DISCORD_WEBHOOK_URL" -H "Content-Type:application/json" -d "{\"content\":null,\"embeds\":[{\"title\":\"Workflow ${{ github.run_id }}\",\"description\":\"A workflow terminou com status $BUILD_RESULT\",\"url\":\"${{ github.event.repository.html_url }}\",\"color\":$BUILD_RESULT_COLOR,\"author\":{\"name\":\"${{ github.repository }}\",\"url\":\"${{ github.event.repository.html_url }}\"},\"footer\":{\"text\":\"${{ github.head_ref }} \u2022 $DATE\"}}]}"

