name: 'Checkout and Test'

on:
 pull_request:
    branches:
      - '**'

jobs:
 checkout_and_test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter    
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests with Coverage
        run: flutter test --coverage

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4.1.2
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # working-directory: /coverage
          update-comment: true  

      - name: Analyze Code
        run: flutter analyze

      - name: Format Code
        run: dart format --output=none --set-exit-if-changed .  
