name: 'Checkout, Setup, Test, Analyze, Format'

on:
  pull_request:
    branches:
      - '**'

permissions:
  pull-requests: write

jobs:

  checkout:
    name: 'Checkout Repository'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  setup_flutter:
    name: 'Set Up Flutter'
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: subosito/flutter-action@v2

  # Combine Install Dependencies and Run Tests with Coverage
  test_with_coverage:
    name: 'Install Dependencies & Run Tests with Coverage'
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - run: flutter pub get
      - run: flutter test --coverage

  # Combine Setup LCOV and Report Code Coverage
  report_coverage:
    name: 'Report Code Coverage'
    runs-on: ubuntu-latest
    needs: test_with_coverage
    steps:
      - uses: hrishikesh-kadam/setup-lcov@v1.0.0
      - uses: kefasjw/lcov-pull-request-report@v1
        with:
          lcov-file: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Code Coverage Report
          all-files-minimum-coverage: 80
          changed-files-minimum-coverage: 80
          artifact-name:  code-coverage

  analyze_and_format:
    name: 'Analyze & Format Code'
    runs-on: ubuntu-latest
    needs: test_with_coverage
    steps:
      - run: flutter analyze
      - run: dart format --output=none --set-exit-if-changed .

