name: 'Checkout and Test'

on:
 pull_request:
    branches:
      - '**'

permissions:
  pull-requests: write

jobs:
  checkout:
    name: 'Checkout'
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter    
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

  analyze:
    name: 'Analyze'
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      
      - name: Analyze Code
        run: flutter analyze

  test:
    name: 'Test'
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      
      - name: Run Tests with Coverage
        run: flutter test --coverage

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1.0.0

      - name: Report code coverage
        uses: kefasjw/lcov-pull-request-report@v1
        with:
          lcov-file: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Code Coverage Report
          all-files-minimum-coverage: 95
          changed-files-minimum-coverage: 95
          artifact-name:  code-coverage
  
  format:
    name: 'Format'
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      
      - name: Format Code
        run: dart format --output=none --set-exit-if-changed .  
    
