name: 'Flutter Setup'

on: 
  workflow_call:
    
jobs:
 setup-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get    